Fitnesspoint/Controllers/DietPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fitnesspoint.Models;
using Fitnesspoint.Db.DbOperations;
namespace Fitnesspoint.Controllers
{
    public class DietPlanController : Controller
    {
        readonly DietPlanDAOImpl impl = new DietPlanDAOImpl();

        // GET: DietPlan/CreateDietPlan
        public ActionResult CreateDietPlan()
        {
            return View();
        }
        // POST: DietPlan/CreateDietPlan
        [HttpPost]
        public ActionResult CreateDietPlan(DietPlanModel dietPlan)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //save data in the database 
                impl.SaveDietPlan(dietPlan);
                //shows message to user if data is inserted
                ViewBag.Message = "Diet Plan Inserted successfully";
                //deletes the data from model
                ModelState.Clear();
            }


            return View();

        }

        // GET: DietPlan/ListAllDietPlans
        [HttpGet]
        public ActionResult ListAllDietPlans()
        {
            //fetch data from all diet plans present in the database 
            var result = impl.FindAllDietPlan();
            //pass the fetched data to View
            return View(result);
        }

        //GET: DietPlan/ShowCalorieContent/diet_id
        public ActionResult ShowCalorieContent(int diet_id)
        {
            //fetch data from diet plan having diet_id equals to DietId present in the database 
            var dietPlan = impl.FindDietPlan(diet_id);
            //pass the fetched data to View
            return View(dietPlan);

        }

        // GET: DietPlan/ChangeDietPlan/diet_id
        public ActionResult ChangeDietPlan(int diet_id)
        {
            //fetch data from diet plan having diet_id equals to DietId present in the database 
            var dietPlan = impl.FindDietPlan(diet_id);
            //pass the fetched data to View
            return View(dietPlan);

        }

        // POST: DietPlan/ChangeDietPlan/diet_id
        [HttpPost]
        public ActionResult ChangeDietPlan(DietPlanModel dietPlan)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //update data in the database based on DietId 
                impl.UpdateDietPlan(dietPlan.DietId, dietPlan);
                //redirect to DietPlan/ListAllDietPlans
                return RedirectToAction("ListAllDietPlans", new { user_id = Session["Id"] });

            }
            return View();

        }

        // GET: DietPlan/RemoveDietPlan/diet_id
        
        public ActionResult RemoveDietPlan(int diet_id)
        {
            //fetch data from diet plan having diet_id equals to DietId present in the database 
            if (ModelState.IsValid)
            {
                //delete data in the database based on DietId 
                impl.DeleteDietPlan(diet_id);
                //redirect to DietPlan/ListAllDietPlans
                return RedirectToAction("ListAllDietPlans", new { user_id = Session["Id"] });
            }
            return View();

        }
       
    }
}

Fitnesspoint/Controllers/NutritionPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fitnesspoint.Models;
using Fitnesspoint.Db.DbOperations;

namespace Fitnesspoint.Controllers
{
    public class NutritionPlanController : Controller
    {
        readonly NutritionPlanDAOImpl impl = new NutritionPlanDAOImpl();
        
        // GET: NutritionPlan/CreateNutritionPlan
        public ActionResult CreateNutritionPlan()
        {
            return View();
        }


        // POST: NutritionPlan/CreateNutritionPlan
        [HttpPost]
        public ActionResult CreateNutritionPlan(NutritionPlanModel nutritionPlan)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //save data in the database 
                impl.SavePlan(nutritionPlan);
                //shows message to user if data is inserted
                ViewBag.Message = "Nutrition Plan Inserted successfully";
                //deletes the data from model
                ModelState.Clear();
            }


            return View();

        }

       
        
        // GET: NutritionPlan/ListAllPlans
        [HttpGet]
        public ActionResult ListAllPlans()
        {
            //fetch data from all nutrition plans present in the database 
            var result = impl.FindAllNutritionPlan();
            //pass the fetched data to View
            return View(result);
        }

       
        
        // GET: NutritionPlan/ListUserAllPlans
        [HttpGet]
        public ActionResult ListUserAllPlans(int User_id, long Contact, string Name)
        {
            Session["User_id"] = User_id;
            Session["Contact"] = Contact;
            Session["Name"] = Name;
            //fetch data from all nutrition plans present in the database 
            var result = impl.FindAllNutritionPlan();
            //pass the fetched data to View
            return View(result);
        }

        // GET: NutritionPlan/ChangePlan/plan_id
        public ActionResult ChangePlan(int plan_id)
        {
            //fetch data from nutrition plan having plan_id equals to NutriPlanId present in the database 
            var nutritionplan = impl.FindNutritionPlan(plan_id);
            //pass the fetched data to View
            return View(nutritionplan);

        }

        // POST: NutritionPlan/ChangePlan/plan_id
        [HttpPost]
        public ActionResult ChangePlan(NutritionPlanModel nutritionPlan)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //update data in the database based on NutriPlanId 
                impl.UpdateNutritionPlan(nutritionPlan.NutriPlanId, nutritionPlan);
                //redirect to NutritionPlan/listAllPlans
                return RedirectToAction("listAllPlans");

            }
            return View();

        }

        // GET: NutritionPlan/RemovePlan/plan_id
        public ActionResult RemovePlan(int plan_id)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //delete data in the database based on NutriPlanId 
                impl.DeleteNutritionPlan(plan_id);
                //redirect to NutritionPlan/listAllPlans
                return RedirectToAction("listAllPlans");
            }
            return View();

        }

        

    }
}

Fitnesspoint/Controllers/WeightLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fitnesspoint.Models;
using Fitnesspoint.Db.DbOperations;

namespace Fitnesspoint.Controllers
{
    public class WeightLogController : Controller
    {
        readonly WeightLogDAOImpl impl = new WeightLogDAOImpl();
        
        // GET: WeightLog/AddWeightLog
        public ActionResult AddWeightLog()
        {
           
            return View();
        }

        // POST: WeightLog/AddWeightLog
        [HttpPost]
        public ActionResult AddWeightLog(WeightLogModel weightLog)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //save data in the database 
                impl.SaveWeight(weightLog);
                //shows message to user if data is inserted
                ViewBag.Message = "Weight Inserted successfully";
                //deletes the data from model
                ModelState.Clear();
                

            }
            return View();

        }

        
        
        // GET: WeightLog/ShowAllWeightLog
        [HttpGet]
        public ActionResult ShowAllWeightLog()
        {
            //fetch data from all weightlogs present in the database 
            var result = impl.FindAllWeight();
            //pass the fetched data to View
            return View(result);
        }

        // GET: WeightLog/UpdateWeightLog/weight_id
        public ActionResult UpdateWeightLog(int weight_id)
        {
            //fetch data from weight log having weight_id equals to WeightId present in the database 
            var weightLog = impl.FindWeight(weight_id);
            //pass the fetched data to View
            return View(weightLog);

        }

        // POST: WeightLog/UpdateWeightLog/weight_id
        [HttpPost]
        public ActionResult UpdateWeightLog(WeightLogModel weightLog)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //update data in the database based on WeightId 
                impl.UpdateWeight(weightLog.WeightId, weightLog);
                //redirect to WeightLog/ShowAllWeightLog
                return RedirectToAction("ShowAllWeightLog", new { user_id=Session["Id"]});

            }
            return View();

        }


        // GET: WeightLog/RemoveWeightLog/weight_id
        public ActionResult RemoveWeightLog(int weight_id)
        {
            //check if the model state is valid or not
            if (ModelState.IsValid)
            {
                //delete data in the database based on WeightId 
                impl.DeleteWeight(weight_id);
                //redirect to WeightLog/ShowAllWeightLog
                return RedirectToAction("ShowAllWeightLog", new { user_id = Session["Id"] });
            }
            return View();


        }


    }
}

Fitnesspoint/Views/Admin/Adminview.cshtml
@{
    ViewBag.Title = "Adminview";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
    Session["Role"] = "Admin";

}

<h2 style="color:mediumseagreen;font-weight:900"><u>Admin Login </u></h2>
<marquee style="color:lightgoldenrodyellow;font-size:medium">Welcome to the admin page</marquee>

<div class="jumbotron" style="background-color:antiquewhite;border:thick;border-block-color:black">
    <h2 style="font-weight:900">User Management</h2>
    <br />
    @Html.ActionLink("View all users >>", "Index", "Admin", new { @class = "btn btn-primary btn-lg" })
    &nbsp;&nbsp;&nbsp;

</div>

<div class="jumbotron" style="background-color:antiquewhite">
    <h2 style="font-weight:900">Nutrition Plan Management</h2>
    <br />
    @Html.ActionLink("View all Nutrition Plans >>", "ListAllPlans", "NutritionPlan", null, new { @class = "btn btn-primary btn-lg" })
    &nbsp;&nbsp;&nbsp;
    @Html.ActionLink("Create a Nutrition Plan >>", "CreateNutritionPlan", "NutritionPlan", null, new { @class = "btn btn-primary btn-lg" })
    &nbsp;&nbsp;&nbsp;
    @Html.ActionLink("View all Diet Plans >>", "ListAllDietPlans", "DietPlan", null, new { @class = "btn btn-primary btn-lg" })
    

</div>

<div class="jumbotron" style="background-color:antiquewhite">
    <h2 style="font-weight:900">Weight Log Management</h2>
    <br />
    
    @Html.ActionLink("View all Weight Logs>>", "ShowAllWeightLog", "WeightLog", null, new { @class = "btn btn-primary btn-lg" })

</div>

Fitnesspoint/Views/Admin/Create.cshtml
@model Fitnesspoint.Db.UserDetail

@{
    ViewBag.Title = "Create";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2 style="color:lightyellow">Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicalCondition, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicalCondition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MedicalCondition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllergicTo, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllergicTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AllergicTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diet_Plan_id, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diet_Plan_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diet_Plan_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goal, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2", @style = "color:antiquewhite;font-weight:900;font-size:larger" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}

<div>
    <p style="text-align:right;font-weight:900;font-size:large">@Html.ActionLink("Back to List", "Index")</p>
</div>

Fitnesspoint/Views/Admin/Delete.cshtml
@model Fitnesspoint.Db.UserDetail

@{
    ViewBag.Title = "Delete";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}



<h3 style="color:lightyellow">Are you sure you want to delete this user ?</h3>
<hr />
<div style="background-color:antiquewhite">

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicalCondition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicalCondition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllergicTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllergicTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diet_Plan_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diet_Plan_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

    </dl>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-primary btn-lg" />
        <p style="text-align:right;font-weight:900;font-size:large">@Html.ActionLink("Back to List", "Index")</p>
    </div>
}

Fitnesspoint/Views/Admin/Details.cshtml
@model Fitnesspoint.Db.UserDetail

@{
    ViewBag.Title = "Details";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2 style="color:lightyellow">Details</h2>

<div>

    <hr />
    <dl class="dl-horizontal jumbotron" style="background-color:antiquewhite">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicalCondition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicalCondition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllergicTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllergicTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diet_Plan_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diet_Plan_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

    </dl>
</div>

@Html.ActionLink("Edit", "Edit", new { id = Model.UserId }, new { @class = "btn btn-primary btn-lg" })
    &nbsp;&nbsp;&nbsp;
<p style="text-align:right;font-weight:900;font-size:large">@Html.ActionLink("Back to List", "Index")</p>

Fitnesspoint/Views/Admin/Index.cshtml
@model IEnumerable<Fitnesspoint.Db.UserDetail>

@{
    ViewBag.Title = "Admin Login";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<br />
<br />
<table class="table" style="background-color:antiquewhite">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalCondition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllergicTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.Goal)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MedicalCondition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AllergicTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Goal)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UserId }, new { @class = "btn btn-primary lg btn-warning" })
                @Html.ActionLink("Details", "Details", new { id = item.UserId }, new { @class = "btn btn-primary lg btn-success" })
                @Html.ActionLink("Delete", "DeleteConfirmed", new { id = item.UserId }, new { @class = "btn btn-primary lg btn-danger", onclick = "return confirm('Are you sure you wish to delete this User?');" })
            </td>
        </tr>
    }

</table>