Fitnesspoint/Controllers/AddCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace Fitnesspoint.Controllers
{
    public class AddCartController : Controller
    {
        // GET: AddCart
        public ActionResult AddCart(string exerciseid)
        {
            ViewBag.exerciseid = exerciseid;

            if (this.Request.RequestType != "POST")
            {
                //adding column into datatable
                DataTable dt = new DataTable();
                DataRow dr;
                dt.Columns.Add("sno");
                dt.Columns.Add("exerciseid");
                dt.Columns.Add("exercisetype");
                dt.Columns.Add("exercisefor");
                dt.Columns.Add("totalset");
                dt.Columns.Add("rest");
                dt.Columns.Add("focus");
                dt.Columns.Add("equipement");
                dt.Columns.Add("time");
                dt.Columns.Add("exercisename");


                if (Request.QueryString["exerciseid"] != null)
                {
                    //Adding the data from data base to cart
                    if (Session["Buyitems"] == null)
                    {

                        dr = dt.NewRow();
                        // Establishing the connection wata database 
                        // Connection by server name and database name
                        string mycon = ConfigurationManager.ConnectionStrings["FitnesspointDatabase"].ConnectionString;
                        SqlConnection scon = new SqlConnection(mycon);
                        String myquery = "select * from exercisedetail where exerciseid=" + Request.QueryString["exerciseid"];
                        SqlCommand cmd = new SqlCommand(myquery,scon);
                        
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        
                        DataSet ds = new DataSet();
                        da.Fill(ds);
                        // using datarow object records added
                        dr["sno"] = 1;
                        dr["exerciseid"] = ds.Tables[0].Rows[0]["exerciseid"].ToString();
                        dr["exercisetype"] = ds.Tables[0].Rows[0]["exercisetype"].ToString();
                        dr["exercisefor"] = ds.Tables[0].Rows[0]["exercisefor"].ToString();
                        dr["totalset"] = ds.Tables[0].Rows[0]["totalset"].ToString();
                        dr["rest"] = ds.Tables[0].Rows[0]["rest"].ToString();
                        dr["focus"] = ds.Tables[0].Rows[0]["focus"].ToString();
                        dr["equipement"] = ds.Tables[0].Rows[0]["equipement"].ToString();
                        dr["time"] = ds.Tables[0].Rows[0]["time"].ToString();
                        dr["exercisename"] = ds.Tables[0].Rows[0]["exercisename"].ToString();
                        dt.Rows.Add(dr);
                        //GridView1.DataSource = dt;
                        // GridView1.DataBind();
                        Session["buyitems"] = dt;
                    }
                   
                    
                    //if records are already added
                    // adding more record 
                    else
                    {

                        dt = (DataTable)Session["buyitems"];
                        int sr;
                        sr = dt.Rows.Count;

                        dr = dt.NewRow();
                        // Establishing the connection wata database 
                        // Connection by server name and database name
                        string mycon = ConfigurationManager.ConnectionStrings["FitnesspointDatabase"].ConnectionString;
                        SqlConnection scon = new SqlConnection(mycon);
                        String myquery = "select * from exercisedetail where exerciseid=" + Request.QueryString["exerciseid"];
                        SqlCommand cmd = new SqlCommand(myquery,scon);
                        
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        
                        DataSet ds = new DataSet();
                        da.Fill(ds);

                        // showing the records in table form
                        // increasing serial number by one
                        dr["sno"] = sr + 1;

                        dr["exerciseid"] = ds.Tables[0].Rows[0]["exerciseid"].ToString();
                        dr["exercisetype"] = ds.Tables[0].Rows[0]["exercisetype"].ToString();
                        dr["exercisefor"] = ds.Tables[0].Rows[0]["exercisefor"].ToString();
                        dr["totalset"] = ds.Tables[0].Rows[0]["totalset"].ToString();
                        dr["rest"] = ds.Tables[0].Rows[0]["rest"].ToString();
                        dr["focus"] = ds.Tables[0].Rows[0]["focus"].ToString();
                        dr["equipement"] = ds.Tables[0].Rows[0]["equipement"].ToString();
                        dr["time"] = ds.Tables[0].Rows[0]["time"].ToString();
                        dr["exercisename"] = ds.Tables[0].Rows[0]["exercisename"].ToString();
                        dt.Rows.Add(dr);
                        // GridView1.DataSource = dt;
                        // GridView1.DataBind();
                        Session["buyitems"] = dt;

                    }
                }
                else
                {
                    dt = (DataTable)Session["buyitems"];
                    // GridView1.DataSource = dt;
                    // GridView1.DataBind();

                }
            }

            return RedirectToAction("Index", "ShowCart");
        }
    }
}

Fitnesspoint/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using Fitnesspoint.Models;
using Fitnesspoint.Db;
using Fitnesspoint.Db.DbOperations;
using System.ComponentModel.DataAnnotations;
using System.Configuration;

namespace Fitnesspoint.Controllers
{
    public class ExerciseController : Controller
    {
        // GET: Exercise
        public ActionResult Exercise()
        {
            return View();

        }
        public ActionResult FatLoss()
        {
            return View();

        }
        public ActionResult MuscleGain()
        {
            return View();

        }
        public ActionResult ChooseGoal()
        {
            TempData["msg"] = "";

            // Establishing the connection wata database 
            // Connection by server name and database name
            
            string mycon = ConfigurationManager.ConnectionStrings["FitnesspointDatabase"].ConnectionString;
            String myquery = "Select * from exercisedetail";
            SqlConnection con = new SqlConnection(mycon);
            SqlCommand cmd = new SqlCommand(myquery,con);
            //cmd.CommandText = myquery;
            //cmd.Connection = con;
            SqlDataAdapter da = new SqlDataAdapter(cmd);
            //da.SelectCommand = cmd;
            DataSet ds = new DataSet();
            da.Fill(ds);
            ExerciseDetails pd1 = new ExerciseDetails();
            List<ExerciseDetails> productlist = new List<ExerciseDetails>();
            // one bye one coulmn is being retrive
            // storing into class object
            for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                ExerciseDetails pd = new ExerciseDetails();
                
                pd.Exerciseid = Convert.ToInt32(ds.Tables[0].Rows[i]["exerciseid"].ToString());
                pd.Exercisetype = ds.Tables[0].Rows[i]["exercisetype"].ToString();
                pd.Exercisefor = ds.Tables[0].Rows[i]["exercisefor"].ToString();
                pd.Totalset = Convert.ToInt32(ds.Tables[0].Rows[i]["totalset"].ToString()); ;
                pd.Rest = ds.Tables[0].Rows[i]["rest"].ToString();
                pd.Focus = ds.Tables[0].Rows[i]["focus"].ToString();
                pd.Equipement = ds.Tables[0].Rows[i]["equipement"].ToString();
                pd.Time = ds.Tables[0].Rows[i]["time"].ToString();
                pd.Exercisename = ds.Tables[0].Rows[i]["exercisename"].ToString();
                
                // a list to receive the data from class object
                productlist.Add(pd);
            }
            // stred all the data
            // closing the connection
            pd1.Productlist = productlist;
            con.Close();
            DataTable dt1 = new DataTable();
            dt1 = (DataTable)Session["buyitems"];
            if (dt1 != null)
            {

                ViewBag.cartnumber = dt1.Rows.Count.ToString();
            }
            else
            {
                ViewBag.cartnumber = "0";
            }
            // returning view of all rceords
            return View(pd1);
        }
    }
}

Fitnesspoint/Views/Exercise/ChooseGoal.cshtml
@model Fitnesspoint.Models.ExerciseDetails

@{ 
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<div class="jumbotron" style="background-color:white">
    <p align="right">
        <i class="fa" style="font-size:25px">&#xf07a;</i>
        <span>@ViewBag.cartnumber</span>
    </p>
    <h2>Choose Your Goal&raquo;</h2>
</div>
@if (Model != null)
{
    if (Model.productlist.Count > 0)
    {
        //creating table to show data which are retrive
<div class="jumbotron" style="background-color:white">
    <font size="4" face="verdana">
        <table border="1" align="center" width="100%" bordercolor="maroon">
            <tr>
                <th>Exercise Type</th>
                <th>Exercise For</th>
                <!--<th>Total Set</th>
                <th>Rest</th>
                <th>Focus</th>
                <th>Equipement</th>
                        <th>Time</th>  -->
                <th>Exercise Name</th>
                <th>Action</th>
            </tr>
            @foreach (var item in Model.productlist)
            {
                <tr>
                    <!--Display the data which are retrive-->
                    <td>@Html.DisplayFor(m => item.exercisetype)</td>
                    <td>@Html.DisplayFor(m => item.exercisefor)</td>
                    <!-- <td>@Html.DisplayFor(m => item.totalset)</td>
                    <td>@Html.DisplayFor(m => item.rest)</td>
                    <td>@Html.DisplayFor(m => item.focus)</td>
                    <td>@Html.DisplayFor(m => item.equipement)</td>
                           <td>@Html.DisplayFor(m => item.time)</td>-->
                    <td>@Html.DisplayFor(m => item.exercisename)</td>
                    <!-- Anchor to go back -->
                    <td>@Html.ActionLink("Add to Cart", "AddCart", "AddCart", routeValues: new { exerciseid = item.exerciseid, }, htmlAttributes: null)</td>
                </tr>
            }
        </table>
    </font>
</div>
            }
            else
            {
            <b>No Details Found.</b>
            }
            }

Fitnesspoint/Views/Exercise/Exercise.cshtml
@{
    ViewBag.Title = "Home Page";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}
<!--Creating a coloured screen-->
<!--Heading over screen-->
<!--Paragraph over screen-->
<div class="jumbotron" style="background-color:antiquewhite">
    <h1>Exercise&raquo;</h1>
    <h4>
        Exercise is any bodily activity that enhances or maintains physical fitness and overall health and wellness.

        It is performed for various reasons, to aid growth and improve strength, preventing aging, developing muscles and the cardiovascular system, honing athletic skills, weight loss or maintenance, improving health..
    </h4>

</div>
<!--Creating a coloured screen-->
<!--block size button-->
<!--Anchor and text over button-->
<div class="jumbotron" style="background-color:azure">
    <p>Choose Your Goal</p>
    <p><a href="~/Exercise/FatLoss" class="btn btn-primary btn-lg btn-block">Loose Fat &raquo;</a></p>
    <p><a href="~/Exercise/MuscleGain" class="btn btn-primary btn-lg btn-block">Gain Muscle &raquo;</a></p>
</div>
<!--A single row having three column-->
<div class="row" style="color:white">
    <div class="col-md-4">
        <h2 style="color:antiquewhite">Get Training Plan</h2>
        <p>
            Get training plan according to you fitness goal and lose weight, tone up, gain muscle, increase cardiovascular fitness, increase strength for a healthier you.
        </p>
        <p><a class="btn btn-primary btn-block">&raquo; &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2 style="color:antiquewhite">Work Hard</h2>
        <p>Stay motivated! Work towards your everyday goal. Stick to your diet and workout plan, find happiness and joy in your workout.</p>
        <p><a class="btn btn-primary btn-block">&raquo; &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2 style="color:antiquewhite">Enjoy Result</h2>
        <p>Set your goal for couple of weeks and work for it. Compare with your previous version, you will proud and happy..</p>
        <p><a class="btn btn-primary btn-block">&raquo; &raquo;</a></p>
    </div>
</div>

Fitnesspoint/Views/Exercise/FatLoss.cshtml
@{
    ViewBag.Title = "FatLoss";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<div class="jumbotron" style="background-color:white">
    <h2>Fat Loss Exercise&raquo;</h2>

</div>
<div class="row" style="color:white">
    <div class="col-md-4">
        <h2>Cardio FatLoss</h2>
        <p>
            cardio exercise is physical exercise of low to high intensity. Cardio exercise is performed by repeating sequences of light-to-moderate intensity exercise activities.
        </p>
        <ul style="font-weight: bold">
            <li>Running, HIIT</li>
            <li>350-750 calorie burn</li>
            <li>No equipement</li>
        </ul>

    </div>
    <div class="col-md-4">
        <h2>Bodyweight Fatloss</h2>
        <p>It is strength-training exercises that use the individual's own weight to provide resistance against gravity. It enhance  biomotor abilities like strength, power, endurance, speed. </p>
        <ul style="font-weight: bold">
            <li>Bodyweight exercise</li>
            <li>250-400 calorie burn</li>
            <li>Basic equipement</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Weightlifting</h2>
        <p>
            Weight lifting training involves the performance of physical exercises which are designed to improve strength and endurance. It is  associated with the use of weights.
            <ul style="font-weight: bold">
                <li>Use of weight</li>
                <li>300-500 calorie burn</li>
                <li>Gym equipement</li>
            </ul>
    </div>
</div>
<div class="jumbotron" style="background-color:white">
    

    <p><a href="~/Exercise/ChooseGoal" class="btn btn-primary btn-lg btn-block">Choose Your Goal &raquo;</a></p>


</div>

Fitnesspoint/Views/Exercise/MuscleGain.cshtml
@{
    ViewBag.Title = "MuscleGain";
    if (User.Identity.IsAuthenticated)
    {
        string role = Session["Role"].ToString();
        if (role == "Admin")
        {
            Layout = "~/Views/Shared/_adminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_userLayout.cshtml";
        }
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<div class="jumbotron" style="background-color:white">
    
    <h2>Muscle Gain Exercise&raquo;</h2>
</div>
<div class="row" style="color:white">
    <div class="col-md-4">
        <h2>Muscle Gain</h2>
        <p>
            it focuses on physical appearance instead of strength. An individual who engages in this activity is referred to as a bodybuilder.
        </p>
        <ul style="font-weight: bold">
            <li>Heavy weight</li>
            <li>400 calorie burn</li>
            <li>Gym equipement</li>
        </ul>
    </div>
</div>
<div class="jumbotron" style="background-color:white">
    

    <p><a href="~/Exercise/ChooseGoal" class="btn btn-primary btn-lg btn-block">Choose Goal &raquo;</a></p>


</div>